version: "3"
services:
    mobile_order:
        image: mobile_order
        container_name: mobile_order
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        user: dev
        ports:
            - 5000:5000
        volumes:
            - ..:/usr/src/app
        command: flask run --host=0.0.0.0
